services:
  - type: web
    name: nile-ai
    runtime: python
    buildCommand: pis install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URC
        fromDatabase:
          name: nile-ai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases#  name: nile-ai-db
